In [9]:
import numpy as np
import pandas as pd

In [10]:
vt = np.random.randint(0,11,5)
vt

array([9, 8, 0, 5, 1])

In [31]:
gj = np.arange(15,56,1)
gj

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [11]:
vtt = np.arange(15,56)
print(vtt[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [12]:
len(vtt)

41

In [41]:
ghg = np.random.randint(1,86,1000)
print(ghg)

[54 82 26 28  5 25 55 78 16 68  6 30 77 25 74 29 70 85  2 42 36  6 54 47
 75 18 43 45 37 82 57 29  5 46 39 34 69 24 44  8 23  7 64 64  3 58  2 31
 45 38 24 49 79 44 57 45 57 32 44 62 38 53  2 75 14 35  6 33  1 49 14 71
 82 75 32 16 64 58 42 77 29 51 68 12 54 68 66 50 62 32 77 44 76 75 45 44
 22 43 16 65 59 17  5 85 21 42 18  5 14 62 25 63 76 76 36 69 34  3 13 76
 84 33 44 59 19 67 54 62  8 28 75  9 75 69 24 41 40 54 37 52 18 28 56 32
 11 71 52 52 17 57 67 61 38 75 39 52 30 69 55  7 66 16  9 79 81 40  3 71
 16 57  9 40 43 17 75 51 60 36 13  9 85 82 46 31 82 82 57 32 11 13 68  4
 50 21 32 49 44 41 63 39 42 56 66 45 26  5 78 33 84  9 72 85 84 76  9 83
 60 78 55 30 35 28 15 40 39  9 13  3 52 82 42 49 36 82  3  5 12 20 69 32
 70  9 52 63 33 17 52 21 70 43 46 64  8 70 22  4  2 52  9 26  5 62 48  9
 18 21 31 41 39 47 34 43  2 12  4 79 40 23 61 23 78 30 54 47 70 44 52 52
 22  8 76 80  2 58 47 26 10 40 62 65 78 66 50 48 75 74 42 63 23 13 22 29
 45 75 64 11 84 26 74 39 38 65 65 23 33  3 29 28 46

In [42]:
bee = np.average(ghg)
bee

43.077

In [43]:
beee = np.var(ghg)
beee

595.123071

In [44]:
gt = np.std(ghg)
gt

24.39514441441165

In [45]:
print('average:',bee,'variance:',beee,'standard deviation:',gt)

average: 43.077 variance: 595.123071 standard deviation: 24.39514441441165


In [46]:
arr = np.array([[1,2,3],[5,6,4],[9,8,7]])
arr

array([[1, 2, 3],
       [5, 6, 4],
       [9, 8, 7]])

In [47]:
yu = np.cumsum(arr, axis = 0)
print('sum over rows\n',yu)

sum over rows
 [[ 1  2  3]
 [ 6  8  7]
 [15 16 14]]


In [48]:
yy = np.cumsum(arr, axis = 1)
print('sum over columns\n',yy)

sum over columns
 [[ 1  3  6]
 [ 5 11 15]
 [ 9 17 24]]


In [49]:
mat = np.array([[9,11],[3,2]])
mat1 = np.array([[6,4],[67,8]])
product = np.dot(mat,mat1)
product

array([[791, 124],
       [152,  28]])