In [54]:
import numpy as np
import pandas as pd

In [55]:
table_x = np.zeros((5,5),dtype=int)

In [56]:
print(table_x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [57]:
table_x[0]=1
table_x[1][0]=1
table_x[2][0]=1
table_x[3][0]=1
table_x[4][0]=1
table_x[1][2]=0
table_x[2][2]=0
table_x[3][2]=0
table_x[4]=1
table_x[1][4]=1
table_x[2][4]=1
table_x[3][4]=1
table_x[2][2]=9


In [58]:
print(table_x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [59]:
gh = pd.DataFrame(table_x)

In [60]:
gh

0  1  2  3  4
0  1  1  1  1  1
1  1  0  0  0  1
2  1  0  9  0  1
3  1  0  0  0  1
4  1  1  1  1  1